# Generated by Django 3.1 on 2022-01-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
    ]
