# Generated by Django 3.1 on 2022-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, null=True)),
                ('receiver', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobApplyer', models.CharField(max_length=50, null=True)),
                ('proposal', models.TextField(null=True)),
            ],
        ),
    ]
