# Generated by Django 3.1 on 2022-01-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stat',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Employer', 'Employer')], max_length=200, null=True),
        ),
    ]
