# Generated by Django 3.1 on 2022-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='val',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
