# Generated by Django 3.1 on 2022-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220115_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
