# Generated by Django 3.1 on 2022-01-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_proposal_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
