# Generated by Django 3.1 on 2022-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220116_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Bio',
            field=models.TextField(blank=True),
        ),
    ]
