# Generated by Django 4.0.1 on 2022-03-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
