# Generated by Django 4.0.1 on 2022-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobCode',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='jobCode',
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.TextField(null=True),
        ),
    ]
